name: API testing

on:
  workflow_dispatch:

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Kill any leftover Chrome or chromedriver processes
      - name: Kill Chrome processes before tests
        run: |
          pkill -f chrome || true
          pkill -f chromedriver || true

      # Clean leftover Chrome user data directories
      - name: Clean Chrome user data directories
        run: |
          rm -rf /tmp/.com.google.Chrome*
          rm -rf /tmp/.org.chromium.Chromium*

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Run API Tests
      - name: Run API Tests
        run: mvn -q clean test -Dtest=**/APITests/*
