on:
  workflow_dispatch:

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Kill Chrome processes before tests
        run: |
          pkill -f chrome || true
          pkill -f chromedriver || true

      - name: Clean Chrome user data directories
        run: |
          rm -rf /tmp/.com.google.Chrome*
          rm -rf /tmp/.org.chromium.Chromium*

      - name: Wait for processes to fully terminate
        run: sleep 5

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run API Tests
        run: mvn -q clean test -Dtest=**/APITests/* -DforkCount=1 -Dparallel=none
