name: WebTable Smoke Tests

on:
  push:
    branches:
      - master

jobs:
  Test:
    name: Execute WebTablesSmokeTest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run WebTablesSmokeTest
        run: |
          mvn -Dtest=WebTablesSmokeTest test -q
