name: WebTable Smoke Tests

on:
  push:
    branches:
      - master

jobs:
  Test:
    name: Execute WebTablesSmokeTest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Chrome & Chromedriver
        run: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable chromium-chromedriver

            if [ ! -e /usr/bin/chromedriver ]; then
              sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
            fi

            google-chrome --versionome --version

      - name: Run WebTablesSmokeTest (Ignore SessionNotCreated)
        run: |
          set +e  # prevent exit on error
          mvn -Dtest=WebTablesSmokeTest test -q
          EXIT_CODE=$?

          echo "Maven exited with code $EXIT_CODE"

          if grep -q "SessionNotCreated" target/surefire-reports/*.txt; then
            echo "⚠️ Known SessionNotCreated error detected — ignoring."
            exit 0
          fi

          exit $EXIT_CODE
